# Generated by Django 2.1.5 on 2019-02-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='rutinas', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'ejercicio',
                'verbose_name_plural': 'ejercicios',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='ejercicios', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('ejercicios', models.ManyToManyField(to='rutina.Ejercicio', verbose_name='Ejercicios')),
            ],
            options={
                'verbose_name': 'rutina',
                'verbose_name_plural': 'rutinas',
                'ordering': ['created'],
            },
        ),
    ]
