# Generated by Django 2.1.5 on 2019-02-18 18:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='descripcion',
            field=ckeditor.fields.RichTextField(max_length=800, verbose_name='Descripción'),
        ),
    ]
