# Generated by Django 2.1.5 on 2019-02-18 18:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0002_auto_20190218_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='descripcion',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=800, verbose_name='Descripción'),
        ),
    ]
