# Generated by Django 2.1.5 on 2019-02-18 19:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0003_auto_20190218_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutinaPersonalizada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descripcion', ckeditor_uploader.fields.RichTextUploadingField(max_length=500, verbose_name='Descripción')),
                ('imagen', models.ImageField(upload_to='ejercicios', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
                ('ejercicios', models.ManyToManyField(to='rutina.Ejercicio', verbose_name='Ejercicios')),
            ],
            options={
                'verbose_name': 'rutinasPersonalizada',
                'verbose_name_plural': 'rutinasPersonalizada',
                'ordering': ['created'],
            },
        ),
    ]
