# Generated by Django 2.1.5 on 2019-02-18 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutina', '0004_rutinapersonalizada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutinapersonalizada',
            name='ejercicios',
            field=models.ManyToManyField(related_name='ejer', to='rutina.Ejercicio', verbose_name='Ejercicios'),
        ),
    ]
