# Generated by Django 2.1.5 on 2019-02-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=500, verbose_name='Dirección')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('imagen', models.ImageField(upload_to='centros', verbose_name='Imagen')),
                ('horario', models.CharField(max_length=300, verbose_name='Horario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'centro',
                'verbose_name_plural': 'centros',
                'ordering': ['-created'],
            },
        ),
    ]
