# Generated by Django 2.1.5 on 2019-02-09 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('duracion', models.IntegerField(verbose_name='Duracion')),
                ('tipo_ejercicio', models.CharField(max_length=200, verbose_name='Tipo de Ejercicio')),
                ('caloria', models.IntegerField(verbose_name='Calorias')),
                ('beneficio', models.CharField(max_length=500, verbose_name='Beneficio')),
                ('imagen', models.ImageField(upload_to='actividades', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'actividad',
                'verbose_name_plural': 'actividades',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=250, verbose_name='Apellidos')),
                ('dni', models.CharField(max_length=100, verbose_name='DNI')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('sexo', models.CharField(max_length=50, verbose_name='Sexo')),
                ('imagen', models.ImageField(upload_to='instructores', verbose_name='Imagen')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Edición')),
            ],
            options={
                'verbose_name': 'instructor',
                'verbose_name_plural': 'instructores',
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='actividad',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividad.Instructor'),
        ),
    ]
