# Generated by Django 2.1.5 on 2019-02-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='especialidad',
            field=models.CharField(default=None, max_length=300, verbose_name='Especialidad'),
            preserve_default=False,
        ),
    ]
